project_id = "xaxbucnjlrfkccsfiddq"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327
file_size_limit = "50MiB"

[auth]
enabled = true
port = 54328
site_url = "https://44d88461-c1ea-4d22-93fe-ebc1a7d81db9.lovableproject.com"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = true
password_min_length = 8

[functions.register-push-subscription]
verify_jwt = false

[functions.daily-driver-payouts]
verify_jwt = false

[functions.manual-driver-payout]
verify_jwt = true

[functions.get-mapbox-token]
verify_jwt = false

[functions.create-test-order]
verify_jwt = true

[functions.send-approval-email]
verify_jwt = true

[functions.send-driver-welcome-email]
verify_jwt = true

[functions.generate-w9]
verify_jwt = true

[functions.send-customer-welcome-email]
verify_jwt = true

[functions.send-restaurant-welcome-email]
verify_jwt = true

[functions.initiate-background-check]
verify_jwt = true

[functions.checkr-webhook]
verify_jwt = false

[functions.create-stripe-connect-account]
verify_jwt = true

[functions.create-stripe-financial-connection]
verify_jwt = true

[functions.calculate-restaurant-readiness]
verify_jwt = true

[functions.create-additional-location]
verify_jwt = true

[functions.admin-verify-business]
verify_jwt = true

[functions.update-menu-preparation-status]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.create-stripe-connect-link]
verify_jwt = true

[functions.get-stripe-connect-status]
verify_jwt = true